name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  altchain_network_monitor_tool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '13'
          architecture: x64
      - name: build
        run:  cd altchain-network-monitor-tool && ./gradlew build
      - name: unarchive
        run:  cd altchain-network-monitor-tool/build/distributions/ && unzip altchain-network-monitor-tool-1.0-SNAPSHOT.zip
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: altchain-network-monitor-tool-1.0-SNAPSHOT
          path: altchain-network-monitor-tool/build/distributions/altchain-network-monitor-tool-1.0-SNAPSHOT
          if-no-files-found: error
